sonar.projectKey=groupesup4_CI-CD-DevOps-Project
sonar.organization=groupesup4
sonar.sources=app/src
# Supprime ou comment la ligne sonar.branch.name pour laisser GitHub Actions décider
# sonar.branch.name=dev2
sonar.javascript.lcov.reportPaths=app/coverage/lcov.info